### ISSUE TITLE
升级iOS12模拟器 缺少c++库

### ISSUE THREAD

**Issue by Zubuntu** [aliyunvideo/AliyunVideoSDKPro#1]
dyld: Library not loaded: /usr/lib/libstdc++.6.dylib
  Referenced from: /Users/zubuntu/Library/Developer/CoreSimulator/Devices/613CFEFA-3C64-46E1-8E4D-257CC3C7542F/data/Containers/Bundle/Application/F2F14C72-317E-42B9-8D1D-E4FB113EDEA9/Nature.app/Frameworks/AliyunVideoSDKPro.framework/AliyunVideoSDKPro
  Reason: no suitable image found.  Did find:
	/usr/lib/libstdc++.6.dylib: mach-o, but not built for iOS simulator

**Comment by aliyunvideo** [comment]
> dyld: Library not loaded: /usr/lib/libstdc++.6.dylib
> Referenced from: /Users/zubuntu/Library/Developer/CoreSimulator/Devices/613CFEFA-3C64-46E1-8E4D-257CC3C7542F/data/Containers/Bundle/Application/F2F14C72-317E-42B9-8D1D-E4FB113EDEA9/Nature.app/Frameworks/AliyunVideoSDKPro.framework/AliyunVideoSDKPro
> Reason: no suitable image found. Did find:
> /usr/lib/libstdc++.6.dylib: mach-o, but not built for iOS simulator

3.6.5.5已经修复，请升级到最新版本
